# Generated by Django 4.0.1 on 2022-08-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrowal',
            name='date_placed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
