# Generated by Django 4.0.1 on 2022-08-25 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_withdrowal_date_placed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wallet_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wallet_type',
        ),
    ]
