# Generated by Django 4.0.1 on 2022-09-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
