# Generated by Django 4.0.1 on 2022-09-15 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_profile_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=60)),
                ('amount', models.FloatField(default=0)),
                ('account_name', models.CharField(blank=True, max_length=60)),
                ('account_number', models.CharField(blank=True, max_length=60)),
                ('bank', models.CharField(blank=True, max_length=60)),
                ('date_placed', models.DateTimeField(auto_now=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('cancel', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Withdrowal',
        ),
    ]
