# Generated by Django 4.0.1 on 2023-01-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_withdraw_delete_withdrowal'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.CharField(blank=True, max_length=35, null=True, unique=True),
        ),
    ]
