# Generated by Django 4.0.1 on 2023-01-12 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_selltrade_buytrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referred',
        ),
        migrations.AddField(
            model_name='profile',
            name='referrals',
            field=models.ManyToManyField(related_name='ref', to=settings.AUTH_USER_MODEL),
        ),
    ]
