# Generated by Django 4.0.1 on 2023-02-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_bonus_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buytrade',
            old_name='usdt',
            new_name='mtc_val',
        ),
        migrations.AddField(
            model_name='buytrade',
            name='sell',
            field=models.BooleanField(default=False),
        ),
    ]
