# Generated by Django 4.0.1 on 2023-02-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_usdt_buytrade_mtc_val_buytrade_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytrade',
            name='usdt',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='selltrade',
            name='usdt',
            field=models.FloatField(default='0.0'),
        ),
    ]
