# Generated by Django 4.0.1 on 2023-02-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_buytrade_usdt_alter_selltrade_usdt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buytrade',
            name='usdt',
        ),
        migrations.RemoveField(
            model_name='selltrade',
            name='usdt',
        ),
    ]
