# Generated by Django 4.0.1 on 2023-02-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='url',
            field=models.URLField(default='https://'),
        ),
    ]
