# Generated by Django 4.0.1 on 2023-02-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_message_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='url',
            field=models.URLField(blank=True, default='https://', null=True),
        ),
    ]
