# Generated by Django 4.0.1 on 2022-08-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_plan_name_deposit_alter_trade_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='due_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='time_now',
            field=models.DateField(),
        ),
    ]
