# Generated by Django 4.0.1 on 2022-08-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_trade_due_time_alter_trade_time_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='due_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='time_now',
            field=models.DateTimeField(),
        ),
    ]
