# Generated by Django 4.0.1 on 2022-08-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_deposit_date_alter_trade_due_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
