# Generated by Django 4.0.1 on 2022-08-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_deposit_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='count',
        ),
        migrations.AddField(
            model_name='trade',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
