# Generated by Django 4.0.1 on 2022-08-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_deposit_count_trade_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
