# Generated by Django 4.0.1 on 2022-08-25 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_plan_min'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandUser',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
