# Generated by Django 4.0.1 on 2022-09-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_delete_randuser_remove_trade_deposit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='option',
            new_name='method',
        ),
        migrations.AddField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='deposit',
            name='usd',
            field=models.FloatField(default=0),
        ),
    ]
