# Generated by Django 4.0.1 on 2023-01-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('date_to', models.DateField()),
                ('interval', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
