# Generated by Django 4.0.1 on 2023-01-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_tradetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradetime',
            name='date_to',
            field=models.DateTimeField(),
        ),
    ]
