# Generated by Django 4.0.1 on 2023-02-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_tradetime_date_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='cap_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
