# Generated by Django 4.0.1 on 2023-02-12 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0014_coin_cap_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('numbers', models.CharField(max_length=30, null=True)),
                ('due_date', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('win', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, null=True)),
                ('stake', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('win', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('lottery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.lottery')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
