# Generated by Django 4.0.1 on 2022-09-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
